smhasher: Set UNALIGNED_SAFE for 64-bit intel too.
This is better for perf, and also happens to suppress a new clang warning:

  PMurHash.c(209,12): error: cast to smaller integer type 'long' from
    'const unsigned char *' is a Microsoft extension [-Werror,-Wmicrosoft-cast]
  int i = -(long)ptr & 3;
  ^~~~~~~~~

64-bit Windows is the only platform I know where long is smaller than
a pointer, and this code is in the !UNALIGNED_SAFE branch. So this patch
addresses the warning.

(Alternatively, we could insert a cast to (uintptr_t) before casting to
long, but the code seems to try to work before C99.)

https://crbug.com/1054220